version: "3"
services:
  app:
    container_name: eonext_frontend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app:cached
    ports:
      - 4001:3000
    tty: true
    stdin_open: true
